### PR TITLE
Don't trim trailing whitespaces for markdown

### PR DESCRIPTION
**Pull request by metalmatze**

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM but you should add this change to all our repos.

**Comment by metalmatze** [comment]
I added it to all I had cloned except gitea itself.

**Comment by tboerger** [comment]
gitea, go-sdk and git also share the same .editorconfig

**Comment by metalmatze** [comment]
I'll do.

**Comment by bkcsoft** [comment]
LGTM

**Pull request merged**
